spring.application.name=backend

# Base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:eduplazas
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Consola web para ver la base de datos en el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Que JPA cree las tablas automáticamente
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ccerveragomez@gmail.com
spring.mail.password=lwnp fzws vkwe qvuh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true